### ISSUE TITLE
is .tool-versions necessary?

### ISSUE THREAD

**Issue by aseigo** [bryanjos/geo#115]
There is an asdf .tool-versions file in the repository. It encodes the following versions:

 erlang 21.1
 elixir 1.7.4-otp-21

both of which are somewhat old by now. More annoyingly, it means that if using asdf (as I do :), unless those exact versions are installed on the system it will not build. I am not sure if those versions are meant as a minimum version of erlang/elixir that must be supported, or if it was merely added as part of a `git add *` type thing.

If it is not intentional, it would be nice to remove that file. If it is intentional, I suppose I can continue to work around it as I currently do :)

**Comment by bryanjos** [comment]
It can be removed and placed in .gitignore
