### ISSUE TITLE
Support for `Feature` and `FeatureCollection` to Geo.JSON

### ISSUE THREAD

**Issue by achedeuzot** [bryanjos/geo#119]
Hi @bryanjos ,

Thanks for this awesome library. Would it be possible to add the support for `Feature` and `FeatureCollection` to follow the specs of https://tools.ietf.org/html/rfc7946#section-3.2 ?

I see something similar exists in the library (see #74) with `GeometryCollection` with properties but it's not compatible with GeoJSON specs. I've been working with multiple GeoJSON files recently and had to first transform standard files for them to work with the lib. 

What do you think about this ? Any way for the `Geo.JSON` module to work seamlessly with `geojson` files ? Thanks !

**Comment by kenichi** [comment]
@achedeuzot #126 has been merged, and i'm curious if it will meet your needs?

**Comment by achedeuzot** [comment]
Awesome @kenichi ! Thanks to your PR & @bryanjos for merging it into the lib ! I'll use it right away :D
