### ISSUE TITLE
Confused about how to use st_within

### ISSUE THREAD

**Issue by arthurcolle** [bryanjos/geo#18]
Hi, I have a User model that has a `field :loc, :geometry` and I have the earthdistance, cube and postgis extensions working on my PG database. I'm confused on how to actually use the st_distance. 

I want to be able to return all users within X miles(or km) of a particular user, given that they have inputted their address and I converted them to lat/long via Google's geocoder library. 

I tried to run the "example_query" in iex as a test and I got an error saying from/2 was not a function:

' from location in Location, limit: 5, select: st_distance(location.geom, ^geom)  '

I then used the exact examples that are in the README, i.e., but I still wasn't able to do a distance query

**Comment by bryanjos** [comment]
Hi,

If you're getting from/2 is not a function, make sure you have imported Ecto.Query. 

I added a test of the example in the docs that should give you an idea.
https://github.com/bryanjos/geo/blob/master/test/geo/ecto_test.exs#L71-L89

As for your actual query, I think it would look something like this:
```elixir
user_id = 1
particular_user = Repo.get(User, user_id)
some_distance = 5

query = from user in User, where: st_distance(user.loc, ^particular_user.loc)  < ^some_distance,  select: user

users = Repo.all(query)
```

I haven't tested it but that's about the gist of it. Of the top of my head I can't remember how postGIS determines the distance between lat/lon points, but you may have to do some conversions to figure out how many miles or km are between them.

Let me know if that helps.

**Comment by arthurcolle** [comment]
Is it just iterating through all users and checking whether the latitude longitude of the origin is within the distance? Or is there some kind of fancy data structure that makes it more efficient than that?

**Comment by bryanjos** [comment]
The macros created in Geo.PostGIS only wrap fragments that add the corresponding functions in PostGIS to the Ecto queries. So the database handles it all. I'm not sure how PostGIS implements ST_Distance.

You can find more info about ST_Distance at the link below
http://www.postgis.org/docs/ST_Distance.html
