### ISSUE TITLE
(ArgumentError) no extension found for oid '8661175'

### ISSUE THREAD

**Issue by bkoltai** [bryanjos/geo#19]
I recently started working on a Phoenix app that shares a Postgres DB with an existing Rails app. The Rails app has a table that I am trying to also access in the Phoenix app called `drivers`, which has a `geo_location` column that is a PostGIS point.

Rails `schema.rb`:
```ruby
create_table "drivers", force: true do |t|
  ...
  t.spatial  "geo_location", limit: {:srid=>4326, :type=>"point", :geographic=>true}
  ...
end
```

The Rails app has been working fine with this in development, the `geo_location` correctly gets stored and the PostGIS extension is definitely enabled on the db.

When I try to connect to the same table via my Phoenix app, I get `(ArgumentError) no extension found for oid '8661175'` 

`mix.exs`
```elixir
  ...
  defp deps do
    [{:phoenix, "~> 0.14"},
     {:phoenix_ecto, "~> 0.5"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 1.1"},
     {:phoenix_live_reload, "~> 0.4", only: :dev},
     {:comeonin, "~> 1.0"},
     {:geo, "~> 0.13.0"},
     {:cowboy, "~> 1.0"}]
  end
  ...
```
`config/dev.exs`
```elixir
config :my_app, MyApp.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "my_db",
  extensions: [{Geo.PostGIS.Extension, library: Geo}],
  size: 10 # The amount of database connections in the pool
```
`web/models/driver.ex`
```elixir
defmodule MyApp.Driver do
  use MyApp.Web, :model

  schema "drivers" do
    field :geo_location, Geo.Point

    field :created_at, Ecto.DateTime
    field :updated_at, Ecto.DateTime
  end
end
```
My attempt to connect via `iex`:
```elixir
iex(4)> MyApp.Repo.all(MyApp.Driver)
** (ArgumentError) no extension found for oid `8661175`
    (postgrex) lib/postgrex/types.ex:282: Postgrex.Types.fetch!/2
    (postgrex) lib/postgrex/types.ex:215: Postgrex.Types.format/2
      (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
      (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
      (elixir) lib/enum.ex:977: Enum.map/2
    (postgrex) lib/postgrex/protocol.ex:124: Postgrex.Protocol.message/3
    (postgrex) lib/postgrex/connection.ex:408: Postgrex.Connection.new_data/2
    (postgrex) lib/postgrex/connection.ex:309: Postgrex.Connection.handle_info/2
```

Any guidance is greatly appreciated

**Comment by bkoltai** [comment]
I've done a little digging and found out that the `geo_location` column is stored as a `geography` in PG. I assume this is why the error is occurring.

Is it hard to support both `geometry` and `geography` types? I'd try to submit a PR for this, but not sure I understand the concepts enough to do it properly.

**Comment by bryanjos** [comment]
Ah, yes the geography data type isn't yet supported, but doing a quick search I see that they are related and it might not be much work to add support for it. The basic idea would be to add another struct for geography, add more pattern matched functions in geo.postgis.extension and add another ecto type for geography. I think most of it would be copying what is there for geometry. I say that without knowing how geographies are returned in queries.

That may give you a high level idea of what's needed. I'll also take a look later tonight to see how simple it would be

**Comment by bryanjos** [comment]
Ok, yeah it won't be a big deal to add support for it. Since geographies are basically just geometries, they could both use the Geometry struct for the time being if that won't be too confusing?

**Comment by bkoltai** [comment]
Yeah, that sounds reasonable. Thanks for looking into it.

**Comment by bryanjos** [comment]
I just updated master with the change.

You can update the geo dep to use the version from github for now to see if it works out for you
```elixir
{:geo, github: "bryanjos/geo"}
```

**Comment by bkoltai** [comment]
Like a charm! Thanks for the fast turn around.

**Comment by bryanjos** [comment]
Awesome! I'll update the docs and put another version into hex pretty soon as well.

**Comment by bryanjos** [comment]
Fyi, I updated the version in hex with the change
{:geo, "~> 0.14.0"}

**Comment by bkoltai** [comment]
Great, thanks.
