### ISSUE TITLE
Cannot JSON encode a point

### ISSUE THREAD

**Issue by bkoltai** [bryanjos/geo#21]
I am trying to return a model that has a `Geo.Point` attribute, and am getting the following Poison error:

```
Poison.EncodeError at PUT /api/driver/update
unable to encode value: {37.7758055, -59.5867633}
```

What is the proper way to JSON encode a `Geo.Point`?

**Comment by bryanjos** [comment]
Ah yeah I don't think Poison works with tuples. If you just want the points, you can turn to tuple into a list and encode that. Or if you want geojson you can use Geo.JSON.encode and pass in the point struct
