### ISSUE TITLE
Add the ability to cast values

### ISSUE THREAD

**Issue by knrz** [bryanjos/geo#26]
I'd like to be able to do:

```elixir
pa = %Geo.Point{coordinates: {40.7127, 74.0059}, srid: 4326}
pb = %Geo.Point{coordinates: {41.8369, 87.6847}, srid: 4326}

query = st_distance({pa, :geography}, {pb, :geography})
# Generates ST_Distance($1::geography, $2::geography).........
```

I'm probably going to have some free time next week to start working on it

**Comment by bryanjos** [comment]
Sounds good! I never really use the geography data type so I'm interested to see how it works. I just assumed those would work the same for geographies but I guess not.

**Comment by bryanjos** [comment]
@knrz is this still an issue for you?

**Comment by knrz** [comment]
It was, but I hard-coded the SQL in my project. I'm busy for a while though, and have no further work that needs the ability to cast.
