### ISSUE TITLE
geo does not compile

### ISSUE THREAD

**Issue by ramky** [bryanjos/geo#27]
I am working on OS X Yosemite, Version 10.10.4.  Elixir version 1.0.5  I am trying to compile geo and it hangs.

mix.exs is as follows

defmodule Geo1.Mixfile do
  use Mix.Project

  def project do
    [app: :geo1,
     version: "0.0.1",
     elixir: "~> 1.0",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  def application do
    [applications: [:logger]]
  end

  defp deps do
    [{:geo, "~> 0.15.0"}]
  end
end

When i compile, it just hangs after lib/geo.ex.  Am i missing anything?

$ mix compile
==> geo
Compiled lib/geo/multi_point.ex
Compiled lib/geo/point.ex
Compiled lib/geo/line_string.ex
Compiled lib/geo/geometry_collection.ex
Compiled lib/geo/multi_line_string.ex
Compiled lib/geo/multi_polygon.ex
Compiled lib/geo/wkb/writer.ex
Compiled lib/geo/wkb/reader.ex
Compiled lib/geo/polygon.ex
Compiled lib/geo/utils.ex
Compiled lib/geo/geo_json.ex
Compiled lib/geo/wkb.ex
Compiled lib/geo/wkt.ex
Compiled lib/geo/postgis.ex
Compiled lib/geo.ex

**Comment by bryanjos** [comment]
Hi, I was able to reproduce it. It's failing because the postgrex dependency is optional (my fault). If you add postgrex as a dependency for now, it should compile. I'll have to take a look and see if there is something I'm doing wrong or if postgrex needs to become a dependency.

**Comment by bryanjos** [comment]
@ramky I just updated the version to include the postgrex dependency. You should be able to just include geo now

`{:geo, "~> 0.16.1"}`

**Comment by ramky** [comment]
It works now, thanks much.
