### ISSUE TITLE
Upgrade :poison to version 2?

### ISSUE THREAD

**Issue by aphillipo** [bryanjos/geo#30]
Might as well get the latest version of poison?

No worries if you know of reasons not to do this...

**Comment by bryanjos** [comment]
It would conflict with ecto's dependency on it which still is for 1.0. And since geo only uses poison when setting up the ecto types, it doesn't make sense right now.

**Comment by bryanjos** [comment]
Looks like the version can be updated using an or (i took a look at how ecto is currently handling it). I need to update the postgrex dependency as well. I'll publish a new version tonight.

**Comment by bryanjos** [comment]
Updated https://hex.pm/packages/geo
