### ISSUE TITLE
No extension found

### ISSUE THREAD

**Issue by YurkoHoshko** [bryanjos/geo#31]
Hi.

Tried to play around with geographic location using your library. In development mode everything is ok, but once release was build in prod mode using exrm I started receiving following error:
`Request: POST /api/reviews
** (exit) an exception was raised:
    ** (ArgumentError) no extension found for oid `17031`
        (postgrex) lib/postgrex/types.ex:298: Postgrex.Types.fetch!/2
        (postgrex) lib/postgrex/types.ex:215: Postgrex.Types.encoder/2
        (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
        (postgrex) lib/postgrex/query.ex:72: DBConnection.Query.Postgrex.Query.encoders/2
        (postgrex) lib/postgrex/query.ex:40: DBConnection.Query.Postgrex.Query.describe/2
        (db_connection) lib/db_connection.ex:884: DBConnection.describe_execute/5
        (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
`

I tried different variations - but still can not find out what could be the root cause of this issue.
Regarding setup - I followed guide in ReadMe - so I have a :geography column in database, postgis enabled and added extensions in config files for Ecto.

**Comment by bryanjos** [comment]
I'm not exactly sure. It sounds like it should work. I don't have much experience with exrm yet unfortunately. It could be related to the configuration. I'm just not sure, but I'll dig around and see if there is something to resolve the issue.

**Comment by YurkoHoshko** [comment]
Hi @bryanjos. 
I fixed this issue. Just got latest exrm, explicitly specified geo in applications and recompiled project. 
Sorry for inconveniences.
