### ISSUE TITLE
Support/Add Docs about Postgis GIS Objects in Migrations

### ISSUE THREAD

**Issue by zmoshansky** [bryanjos/geo#33]
First, thank you very much for this library!

AFAIK, Geo doesn't migrations with advanced types like `geometry(Point,4326)` etc. If that's correct, some documentation on how to use/drawing attention to the abilities of Postgis GIS Objects with Geo would be very helpful (for newcomers like myself....).

#### Postgis Migrations Example
To add a basic geometry type in a migration:
```
  def change do
    create table(:address) do
       ....
       add :geom, :geometry
    end
```

Or, if you would like to use more advanced types see [Postgis GIS Objects](http://postgis.net/docs/using_postgis_dbmanagement.html#RefObject). These types are useful for enforcing constraints on {Lng,Lat} (order matters), or ensuring that a particular projection/representation is used, etc.

```
  def change do
    create table(:address) do
       ....
    end
    execute("SELECT AddGeometryColumn ('address','lng_lat_point',4326,'POINT',2);")
```

**Comment by bryanjos** [comment]
Hi! You are correct on the advanced types (unless Ecto does support it and I don't know the correct syntax). I can add some documentation around migrations

**Comment by bryanjos** [comment]
Actually @zmoshansky could I use the text you have here? Or maybe you can do it in a PR on the README?
