### ISSUE TITLE
Elixir 1.3 Warnings

### ISSUE THREAD

**Issue by benwilson512** [bryanjos/geo#40]
Hey!

Just upgraded to Elixir 1.3, and there's a fair number of warnings, largely about imperative `if` cases. Happy to look into doing a PR, just thought I'd note it down here first.

Thanks!

- Ben

**Comment by bryanjos** [comment]
Hi! I'm sure there are a bunch. A PR would definitely be appreciated. I've been going through my other projects since 1.3 was released and fixing the warnings in those.

**Comment by bryanjos** [comment]
Small warning: A lot of the code, especially in wkt, wkb, and utils were written when I was still an Elixir newbie and before Elixir 1.0. It might not be fun to look at 😄 . They are on my eventual list to improve.

**Comment by benwilson512** [comment]
No problem, I know I sure have plenty of code like that too :)
