### ISSUE TITLE
Investigate using more than one geometry type for a column

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/geo#43]
This is an issue to check if it is possible to insert more than one type (point, line, etc) into a column when using geo with an Ecto schema. If it is currently possible, document how to. If it is not currently possible, come up with a plan to make it so.

**Comment by jerel** [comment]
What about a `Geo.Geometry` field type that accepts any of the valid geometries instead of just one type? I'm not having any luck getting this to work with the existing fields.

**Comment by bryanjos** [comment]
Yeah that's what I'm thinking too.
https://hexdocs.pm/ecto/Ecto.Type.html

I'm thinking maybe making one custom ecto type that accepts any of the geo types may do the trick. I can give it a shot later today hopefully.

**Comment by bryanjos** [comment]
Updated geo to 1.1
https://hex.pm/packages/geo

In this version there is `Geo.Geometry`. Use that in your Ecto schema to allow multiple types of geometry in a single field. I updated the README to show using it.

**Comment by bryanjos** [comment]
@jerel let me know if that works for you

**Comment by jerel** [comment]
@bryanjos this works fantastic! Thanks so much for adding it in
