### ISSUE TITLE
Getting error "no function clause matching in Geo.JSON.do_encode/1" when trying to pretty print an object

### ISSUE THREAD

**Issue by acrolink** [bryanjos/geo#44]
I am trying to print an object inside a view template with:

```
<%= IO.inspect Geo.JSON.encode(@policies) %>
```

but I am getting the error:

```
no function clause matching in Geo.JSON.do_encode/1
```

What is going on here? Thanks.

**Comment by bryanjos** [comment]
What exactly is `@policies`? If it isn't one of the supported types, then Geo will not be able to encode it.

https://github.com/bryanjos/geo/blob/master/lib/geo/geo_json.ex#L112-L164

Saying that, I think I will make another function head that covers everything else and throws an error if it isn't one of the Geo types

**Comment by acrolink** [comment]
Thank you very much @bryanjos for the clarification.

**Comment by bryanjos** [comment]
No problem. I just published a patch that will throw a more informative error whenever encoding or decoding a value from the Geo.JSON module
