### ISSUE TITLE
Trying to run in dev- error: type geometry can not be handled

### ISSUE THREAD

**Issue by eamonpenland** [bryanjos/geo#55]
Trying to run this package in dev, but I'm not sure how to get it configured properly:

**- created migration**
```
  def up do
    execute "CREATE EXTENSION IF NOT EXISTS postgis"
  end

  def down do
    execute "DROP EXTENSION IF EXISTS postgis"
  end
```

**- created point on new table column**
```
      add :state, :string
      add :postal, :string
      add :geom, :geometry
      add :radius, :integer
```

**- had to update poison for phoenix** 
`{:poison, "~> 3.0", override: true},`

**- created postgres_types.ex file**
```
Postgrex.Types.define(MyApp.PostgresTypes,
                      [Geo.PostGIS.Extension] ++ Ecto.Adapters.Postgres.extensions(),
                      json: Poison)
```

**- test.ex added types** 
`types: LocalistApi.PostgresTypes`

**- get error ->**
`type `geometry` can not be handled by the configured extensions`

**- if I add `types: LocalistApi.PostgresTypes` to my dev.exs file i get this error**
`function MyApp.PostgresTypes.encode_params/2 is undefined (module MyApp.PostgresTypes is not available)`

can you please help me understand what I am missing/doing incorrectly? Thanks!

**Comment by bryanjos** [comment]
I think the issue may be in your `postgres_types.ex` file. Replace `MyApp.PostgresTypes` with `LocalistApi.PostgresTypes`. In other words, make sure the module you define with `Postgrex.Types.define` and the value you give to the `types` parameter match.

On the poison dependency, I think I'm going to make an update to relax the version needed

**Comment by eamonpenland** [comment]
Sorry they do match. I was trying to redact the name of my app but wasn't consistent.

**Comment by eamonpenland** [comment]
ya i just can't figure out what I'm missing. is there an example of this working with the latest release of postgrex? I've found other examples of this library working with postgrex 12.1.0.

**Comment by bryanjos** [comment]
You can look at this project for an example: https://github.com/bryanjos/geo_example

**Comment by eamonpenland** [comment]
awesome! thanks for the quick response! At first your example project wasn't working, so i figured it was an env thing. brew upgraded updated everything and it worked. Thanks again!!

**Comment by choiway** [comment]
@eamonpenland I'm having the same series of errors. What did you end up upgrading / updating? Thanks.
