### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by aaboyd** [bryanjos/geo#59]
Could you add a LICENSE file to this repo?

I noticed some of your other code is MIT Licensed, is there any reason to believe this code would be any different?

**Comment by bryanjos** [comment]
It's MIT: https://github.com/bryanjos/geo/blob/master/mix.exs#L46

If it makes sense to add a license file, I can add one

**Comment by aaboyd** [comment]
No that works for me.  Sorry, I missed that.  Was looking for the LICENSE file in the root of the repo that you see so often.  As long as it has a license, I'm all set.

Thanks for the library!

**Comment by bryanjos** [comment]
Thanks! I'll probably just add one anyway to make it clearer
