### ISSUE TITLE
Module Ecto.Adapters.Postgres is not available

### ISSUE THREAD

**Issue by steffenix** [bryanjos/geo#60]
I was using 1.2.1 with elixir 1.2 and postgresx 0.12.
Now I am trying to update to 1.3.1 elixir 1.4 and postgresx 0.13

When I am configuring the types I am getting `Module Ecto.Adapters.Postgres is not available` before I was using the extension option, any clues?

```
Postgrex.Types.define(Stef.PostgresTypes,
              [Geo.PostGIS.Extension] ++ Ecto.Adapters.Postgres.extensions(),
              json: Poison)
```

**Comment by bryanjos** [comment]
Hi, I'm not sure from the information given, but if you're using just Postgrex without Ecto then that line would be different. You wouldn't need to add `Ecto.Adapters.Postgres.extensions()`

If you are using it with Ecto than this might be an Ecto specific issue.

You can also have a look at this example project I made to setup geo with new ecto:
https://github.com/bryanjos/geo_example

**Comment by steffenix** [comment]
Thanks for the example I will have a look, I was trying to use `Ecto.Adapters.Postgres.extensions()` in the config file.

**Comment by bryanjos** [comment]
@steffenix all good? If so I can close this issue

**Comment by steffenix** [comment]
All good.
