### ISSUE TITLE
Separate Postgrex extension into it's own library

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/geo#73]
It is beneficial to some to have the WKB, WKT, and GeoJSON parts of Geo without the PostGIS parts. This is a proposal to make the PostGIS parts into it's own library. This would include the Postgrex extension along with the PostGIS macros. This would be a breaking change so Geo would be bumped to 2.0.0

**Comment by dpehrson** [comment]
That would be in line with the pattern that @dazuma took with rgeo/rgeo I believe.

It would be excellent if the community could build an group of libraries for all aspects of geospatial stuff in Elixir. Problems that I can think of off the top of my head:

- General geo object/algorithm library
- Storage-specific libraries (PostGIS, etc.)
- File format-specific libraries (GPX, Shapefile, GeoJSON, etc.)
- Ecto integration

It would be wonderful if we could build libraries that all work with each other seamlessly and share data structures, etc.

I do not need geospatial stuff yet, but I will be needing it in the near future, so I'm happy to help provide any feedback I can.

**Comment by samphilipd** [comment]
+1 for this. I am adding geometry support to mariaex and it would be nice to reuse the logic in this library without pulling in all of the Postgres-specific stuff.

**Comment by bryanjos** [comment]
Published version 2.0.0 that removes the optional postgrex dependency. It does keep the Ecto Types though
