### ISSUE TITLE
Implement Poison.Decoder

### ISSUE THREAD

**Issue by jaysson** [bryanjos/geo#80]
Many times, it is a lot easier to return the record fetched from db in a controller like this:

```elixir
def show(conn, params)
  address = Repo.get!(Address, params["id"])
  json conn, address
end
```
However, the address has a `Geo.Point` field, and poison does not know how to decode it. It would be great if an implementation for `Poison.Decoder` could be added.

**Comment by yordis** [comment]
@jaysson did you call 

```elixir
Geo.JSON.encode(address.geo_location) |> Poison.encode!()
```

or whichever other field and see if it works?

Also, I don't believe this package should be tide to `Poison.Decoder`, what happened if I don't want to use Poison for my JSON encoding and decoding? That is the reason why Poison is added as optional deps.

Also, you could do something like

```elixir
defimpl Poison.Encoder, for: Geo.Point do
  def encode(struct, options) do
     # ...
  end
end
```

**Comment by yordis** [comment]
Actually looking the code I think that this package depends of Poison instead of being configurable ...

**Comment by bryanjos** [comment]
This is no longer applicable here
