### ISSUE TITLE
Move Ecto specific code to geo_ecto

### ISSUE THREAD

**Issue by yordis** [bryanjos/geo#84]
Many of the modules depends of Ecto just for the types,

from the Core perspective, Geo doesn't need to implement something related to Ecto. Most of the Geo packages could become leaner so it will become more easier to maintain the core of the package.

Also,

Moving this to independent package is welcoming to more advance code for Ecto related stuff, for example.

https://github.com/bryanjos/geo/blob/ac5990e5c09f56528ca47d0deae96bb9d5d69a8e/lib/geo/point.ex#L26

This is assuming that everyone will be using GeoJSON but right now I am interested in use the other packages formatting. So we would need to configure which formatter I will be using on my platform (maybe we will end up doing `Geo.Ecto.GeoJSON.Point` or `Geo.Ecto.WKT.Point` because we do not want to configure globally the formatter being used)

**Comment by bryanjos** [comment]
`Ecto.DataType` protocol might be an alternative. But not sure how that effects things.

So I guess I'm willing to see `Ecto.DataType` implemented instead as long as things work as is, or the differences are known and documented

**Comment by yordis** [comment]
@bryanjos the concern I have is when I dont want to GeoJSON as my formatting for example.

Because of this, when you do `field :name, Geo.[Type]` we will need to have 3 different types for `Point` for example.

`Geo.JSON.Point`, `Geo.WKT.Point`, `Geo.WKB.Point` unless we use a generic one that fallbacks back to each formatter (which I would like to not do that).

Unless we roll with just one and create some changesets that transform from on formatting to the other.

Not quite sure what is the best movement here, GeoJSON is perfect if you don't care about saving a bunch of bytes, which for some could be the concern, I guess.

**Comment by bryanjos** [comment]
I'm not sure I understand what is meant, having three structs for the same type isn't something I'm willing to accept. Unless there is a way to move the ecto-specific code to geo_ecto and keep functionality the same, I would say to keep things the same until a time where it is possible

**Comment by bryanjos** [comment]
I can do some exploratory work to see if it's possible

**Comment by yordis** [comment]
@bryanjos I dont need 3 different ecto types for each data type but don't forget that some people could be interested in specific formatter over GeoJSON, that is why I am bringing it into the table so we think about it.

**Comment by bryanjos** [comment]
@yordis I was able to move ecto code to geo_postgis completely
