### ISSUE TITLE
Improve WKB and WKT encoder/decoder

### ISSUE THREAD

**Issue by yordis** [bryanjos/geo#86]
We should try to follow the convention of the JSON parser where we have the `!` functions that raise an error and the regular one that give a tuple back

WKB
- [ ] Add encode!
- [ ] Add encode
- [ ] Add decode
- [ ] Add decode!

WKT
- [ ] Add encode!
- [ ] Add encode
- [ ] Add decode
- [ ] Add decode!

**Comment by bryanjos** [comment]
Fixed in 8a9d471d48771d1233073997b5bff0436e8249f3
